name: Hello World Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - development

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello World
        run: echo "Hello, World!"  
